apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o7483ky3d-go 
  janus-idp.io/tekton: o7483ky3d-go
  backstage.io/kubernetes-id: o7483ky3d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7483ky3d-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml